
# This worklflow will perform following actions when the code is pushed to development branch:
# - Build the latest docker image in development which needs test to pass first.
# - Push the docker image to Github Artifact Registry-Dev.
# 
# Maintainers:
#   - name: Nisha Sharma
#   - email: nisha.sharma@uni-jena.de

name : Dev Build, Test and Publish

on:
  push:
    branches: [development]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-west3-a
  REPOSITORY_NAME: nmrxiv-dev
  APP_IMAGE: nmr-predict

jobs:
  setup-build-publish-dev:
    name: Build & publish to dev registry
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Setup CLI
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Configure docker
      run: |-
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    # Build the Docker image
    - name: Build docker image
      run: |-
        docker build --tag "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest" .

    # Push the Docker image to Google Container Registry
    - name: Publish image to Google Artifact Registry
      run: |-
        docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest"